### ISSUE TITLE
Requested too many items

### ISSUE THREAD

**Issue by TheHolyWaffle** [JuicyPasta/reddit-snooper#2]
Using the following snippet results in the message `Requested too many items (reddit does not keep this large of a listing)`:
```
this._snooper.watcher.getPostWatcher('all')
    .on('post', function(post) {
        //...
    })
    .on('error', console.error)
```

This is my configuration (taken from the README):
```
this._snooper = new Snooper({
        app_id: '<redacted>',
        api_secret: '<redacted>',
        user_agent: '<redacted>',
        automatic_retries: true, 
        api_requests_per_minuite: 60
    });
```

**Comment by JuicyPasta** [comment]
Reddit will only store the front page listings for a certain amount of time before they are unlisted. In this time, if your system is not able to process a message before it is unlisted (slow internet speeds most likely). the aforementioned error will be thrown and the watcher will cut its losses and keep going. The error message should say something like "possible item loss", 


I just thought of a good way to get around this problem for watching 'all', I'll close this issue when it's pushed out

**Comment by dowzhong** [comment]
when is that going to happen? Im getting this problem too.
